# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: François Févotte
email: fevotte@gmail.com
description: >
  Professional web site for François Févotte.
baseurl: ""
url: "http://www.fevotte.net"
github_username:  ffevotte
google_analytics: UA-96655077-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _site
  - _preview
  - _cv
  - bibtex2html-1.98-linux
  - bibtex2html-1.98-linux.tar.gz
  - font-awesome-4.7.0.zip
  - env.el
  - Makefile

nav:
  - ["Publications", "/publications/"]
  - ["Teaching",     "/teaching/"]
  - ["CV",           "/cv/"]
